-- AUTO INCREMENT FOR BIDS
CREATE SEQUENCE bid_seq START WITH 1;

CREATE OR REPLACE TRIGGER bid_bir
BEFORE INSERT ON bids
FOR EACH ROW

BEGIN
  SELECT bid_seq.NEXTVAL
  INTO   :new.bid_id
  FROM   dual;
END;