-- AUTO INCREMENT FOR USERS
CREATE SEQUENCE user_seq START WITH 1;

CREATE OR REPLACE TRIGGER user_bir
BEFORE INSERT ON users
FOR EACH ROW

BEGIN
  SELECT user_seq.NEXTVAL
  INTO   :new.user_id
  FROM   dual;
END;