-- AUTO INCREMENT FOR ITEMS
CREATE SEQUENCE item_seq START WITH 1;

CREATE OR REPLACE TRIGGER item_bir
BEFORE INSERT ON items
FOR EACH ROW

BEGIN
  SELECT item_seq.NEXTVAL
  INTO   :new.item_id
  FROM   dual;
END;